List<Item> items = [
  Item(
    id: "1",
    title: "Diary milk",
    price: 10.99,
    description: "Delicious milk chocolate",
    imageUrl: "https://5.imimg.com/data5/SELLER/Default/2023/2/DZ/YH/EC/15355181/prod-20211227-1807503220564475383400315-jpg-500x500.jpg",
    quantity: 50,
  ),
  Item(
    id: "2",
    title: "KitKat",
    price: 8.99,
    description: "Crunchy wafer chocolate bar",
    imageUrl: "https://m.media-amazon.com/images/I/51xW9xPBN3L._SX522_.jpg",
    quantity: 30,
  ),
  Item(
    id: "3",
    title: "Twix",
    price: 9.99,
    description: "Caramel and cookie chocolate bar",
    imageUrl: "https://m.media-amazon.com/images/I/5174rfQNeIL._SX466_.jpg",
    quantity: 25,
  ),
  Item(
    id: "4",
    title: "5-star",
    price: 7.99,
    description: "Rich and smooth chocolate bar",
    imageUrl: "https://m.media-amazon.com/images/I/618fySthK8L._SX522_.jpg",
    quantity: 40,
  ),
  Item(
    id: "5",
    title: "Oreo",
    price: 5.99,
    description: "Chocolate sandwich cookies",
    imageUrl: "https://m.media-amazon.com/images/I/61-pXsfgjTS._SL1500_.jpg",
    quantity: 60,
  ),
  Item(
    id: "6",
    title: "Hide & seek",
    price: 6.99,
    description: "Crunchy chocolate chip cookies",
    imageUrl: "https://m.media-amazon.com/images/I/61OZQN4AQ5L._SL1200_.jpg",
    quantity: 35,
  ),
  Item(
    id: "7",
    title: "Dark fantasy",
    price: 8.99,
    description: "Rich and indulgent chocolate cookies",
    imageUrl: "https://m.media-amazon.com/images/I/81gzAVquhUL._SL1500_.jpg",
    quantity: 45,
  ),
  Item(
    id: "8",
    title: "Lottle pie",
    price: 12.99,
    description: "Delicious fruit-filled mini pies",
    imageUrl: "https://m.media-amazon.com/images/I/51sAiup+ppL.jpg",
    quantity: 20,
  ),
  Item(
    id: "9",
    title: "Pen",
    price: 1.99,
    description: "Blue ballpoint pen",
    imageUrl: "https://example.com/pen.jpg",
    quantity: 100,
  ),
  Item(
    id: "10",
    title: "Pencil",
    price: 0.99,
    description: "Wooden graphite pencil",
    imageUrl: "https://example.com/pencil.jpg",
    quantity: 80,
  ),
  Item(
    id: "11",
    title: "Scale",
    price: 2.99,
    description: "Plastic ruler",
    imageUrl: "https://example.com/scale.jpg",
    quantity: 50,
  ),
  Item(
    id: "12",
    title: "Toothpaste",
    price: 4.99,
    description: "Mint-flavored toothpaste",
    imageUrl: "https://example.com/toothpaste.jpg",
    quantity: 30,
  ),
  Item(
    id: "13",
    title: "Brush",
    price: 3.99,
    description: "Soft-bristle toothbrush",
    imageUrl: "https://example.com/brush.jpg",
    quantity: 40,
  ),
  Item(
    id: "14",
    title: "Bodywash",
    price: 7.99,
    description: "Refreshing body wash",
    imageUrl: "https://example.com/bodywash.jpg",
    quantity: 25,
  ),
  Item(
    id: "15",
    title: "Facewash",
    price: 6.99,
    description: "Gentle facial cleanser",
    imageUrl: "https://example.com/facewash.jpg",
    quantity: 30,
  ),
  Item(
    id: "16",
    title: "Loofah",
    price: 2.99,
    description: "Exfoliating bath sponge",
    imageUrl: "https://example.com/loofah.jpg",
    quantity: 50,
  ),
  Item(
    id: "17",
    title: "Shampoo",
    price: 9.99,
    description: "Nourishing hair shampoo",
    imageUrl: "https://example.com/shampoo.jpg",
    quantity: 30,
  ),
  Item(
    id: "18",
    title: "Conditioner",
    price: 9.99,
    description: "Hydrating hair conditioner",
    imageUrl: "https://example.com/conditioner.jpg",
    quantity: 30,
  ),
  Item(
    id: "19",
    title: "Hair pins",
    price: 1.99,
    description: "Set of hair pins",
    imageUrl: "https://example.com/hair_pins.jpg",
    quantity: 50,
  ),
  Item(
    id: "20",
    title: "Tops",
    price: 19.99,
    description: "Women's casual top",
    imageUrl: "https://example.com/tops.jpg",
    quantity: 15,
  ),
  Item(
    id: "21",
    title: "Pyjamas",
    price: 15.99,
    description: "Comfortable sleepwear",
    imageUrl: "https://example.com/pyjamas.jpg",
    quantity: 20,
  ),
  Item(
    id: "22",
    title: "Kurti",
    price: 24.99,
    description: "Traditional Indian women's attire",
    imageUrl: "https://example.com/kurti.jpg",
    quantity: 10,
  ),
  Item(
    id: "23",
    title: "Plazo",
    price: 18.99,
    description: "Wide-legged trousers",
    imageUrl: "https://example.com/plazo.jpg",
    quantity: 15,
  ),
  Item(
    id: "24",
    title: "Bournvita",
    price: 11.99,
    description: "Health drink mix",
    imageUrl: "https://example.com/bournvita.jpg",
    quantity: 40,
  ),
  Item(
    id: "25",
    title: "Nutella",
    price: 8.99,
    description: "Hazelnut spread",
    imageUrl: "https://example.com/nutella.jpg",
    quantity: 30,
  ),
  Item(
    id: "26",
    title: "Jam",
    price: 5.99,
    description: "Fruit jam",
    imageUrl: "https://example.com/jam.jpg",
    quantity: 35,
  ),
  Item(
    id: "27",
    title: "Bread",
    price: 3.99,
    description: "White bread loaf",
    imageUrl: "https://example.com/bread.jpg",
    quantity: 40,
  ),
  Item(
    id: "28",
    title: "Bag",
    price: 29.99,
    description: "Stylish backpack",
    imageUrl: "https://example.com/bag.jpg",
    quantity: 10,
  ),
  Item(
    id: "29",
    title: "Shoes",
    price: 39.99,
    description: "Running shoes",
    imageUrl: "https://example.com/shoes.jpg",
    quantity: 8,
  ),
  Item(
    id: "30",
    title: "Chappal",
    price: 14.99,
    description: "Casual sandals",
    imageUrl: "https://example.com/chappal.jpg",
    quantity: 12,
  ),
  Item(
    id: "31",
    title: "Perfume",
    price: 29.99,
    description: "Fragrance for men",
    imageUrl: "https://example.com/perfume.jpg",
    quantity: 20,
  ),
];

class Item {
  final String id;
  final String title;
  final double price;
  final String description;
  final String imageUrl;
  final int quantity;

  Item({
    required this.id,
    required this.title,
    required this.price,
    required this.description,
    required this.imageUrl,
    required this.quantity,
  });
}
